export { default as Layout } from "./Layout"
export { default as Home } from "./Home"
export { default as Products } from "./Products"
export { default as SinglePage } from "./SinglePage"
export { default as Account } from "./Account"
export { default as Cart } from "./Cart"
export { default as Checkout } from "./Checkout"
export { default as Orders } from "./Orders"
export { default as Register } from "./Register"
export { default as Auth } from "./Auth"
export { default as Wishlist } from "./Wishlist"
// export { default as Layout } from "./Layout"
// export { default as Layout } from "./Layout"
// export { default as Layout } from "./Layout"
// export { default as Layout } from "./Layout"
export { default as NotFound } from "./NotFound"